### ISSUE TITLE
Missing `FilterQuality` parameter

### ISSUE THREAD

**Issue by EugeneZaitsev** [BobLd/PdfPig.Rendering.Skia#21]
I noticed that `SKPaintCache` uses `SKPaint` with `IsAntialias` set to true. But looks like for images that is not enough, `FilterQuality` should also be set to some value different from `None`, otherwise all images look pixelated.

**Comment by BobLd** [comment]
thx @EugeneZaitsev, I'll look into that shortly

**Comment by BobLd** [comment]
now fixed. fyi some tests are now failing but this is expected. The expected images need to be updated to match the new filter quality
